# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uoh-software-project-time-report',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/uoh-software-project-time-report',
                'lib_path': 'uoh_software_project_time_report'},
  'syms': { 'uoh_software_project_time_report.core': { 'uoh_software_project_time_report.core.foo': ( 'core.html#foo',
                                                                                                      'uoh_software_project_time_report/core.py')}}}
